# Generated by Django 4.1.7 on 2023-03-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40)),
                ("text", models.TextField()),
                ("posted_at", models.DateField()),
                ("updated_at", models.DateField()),
            ],
        ),
    ]
