# Generated by Django 4.1.7 on 2023-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(null=True, upload_to="media/images/"),
        ),
    ]
